### ISSUE TITLE
Serialization of File is not allowed

### ISSUE THREAD

**Issue by Cypaubr** [dustin10/VichUploaderBundle#1101]
|    Q        |   A
|------------ | -----
| Version     | 1.13.1

### Support Question

I have an User with a `imageFile` field (of type `Symfony\Component\HttpFoundation\File`).

Today when I tried to login to my app I got this error in production:
```
Exception: Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed
#11 /vendor/symfony/security-core/Authentication/Token/AbstractToken.php(181): serialize
#10 /vendor/symfony/security-core/Authentication/Token/AbstractToken.php(181): Symfony\Component\Security\Core\Authentication\Token\AbstractToken::serialize
#9 [internal](0): serialize
#8 /vendor/symfony/security-http/Firewall/ContextListener.php(193): Symfony\Component\Security\Http\Firewall\ContextListener::onKernelResponse
#7 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#6 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#5 /vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#4 /vendor/symfony/http-kernel/HttpKernel.php(179): Symfony\Component\HttpKernel\HttpKernel::filterResponse
#3 /vendor/symfony/http-kernel/HttpKernel.php(125): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
#0 /public/index.php(25): null
```

The imageName field is initialized with 'default.png'.

**Comment by garak** [comment]
This has been discussed in many old issues
