### ISSUE TITLE
Simple default way of deleting images

### ISSUE THREAD

**Issue by Remonell** [dustin10/VichUploaderBundle#1206]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.16.1
| Symfony version | 5.1
| PHP version     | 7.3

### Support Question

What is the default way to delete an image that has been uploaded via VichUploader? I am using Symfony/Doctrine in the backend and GraphQL. Creating and uploading files works. File also gets created in the proper directory.

This is what my entitiy looks like:

```
/**
 * @ORM\Entity(repositoryClass=DeviceImageRepository::class)
 * @ApiResource(
 *     attributes={"order"={"imageName": "ASC"}},
 *     collectionOperations={
 *         "post"={
 *             "controller"=UploadDeviceImageAction::class,
 *             "deserialize"=false,
 *             "openapi_context"={
 *                 "requestBody"={
 *                     "content"={
 *                         "multipart/form-data"={
 *                             "schema"={
 *                                 "type"="object",
 *                                 "properties"={
 *                                     "deviceId"={
 *                                          "type"="string"
 *                                     },
 *                                     "imageFile"={
 *                                         "type"="string",
 *                                         "format"="binary"
 *                                     },
 *                                     "imageType"={
 *                                          "type"="string"
 *                                     },
 *                                     "base64"={
 *                                          "type"="string"
 *                                     },
 *                                     "createdBy"={
 *                                         "type"="string"
 *                                     },
 *                                     "modifiedBy"={
 *                                         "type"="string"
 *                                     },
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         "get"
 *     },
 *     itemOperations={
 *         "get",
 *         "delete",
 *         "put",
 *         "patch",
 *     },
 *     graphql={
 *         "item_query",
 *         "collection_query",
 *         "delete",
 *         "update",
 *         "create",
 *         "upload"={
 *             "mutation"=UploadDeviceImageMutationResolver::class,
 *             "deserialize"=false,
 *             "args"={
 *                 "deviceId"={"type"="String!"},
 *                 "imageFile"={"type"="Upload!"},
 *                 "imageType"={"type"="String!"},
 *                 "base64"={"type"="String"},
 *                 "createdBy"={"type"="String"},
 *                 "modifiedBy"={"type"="String"},
 *             }
 *         }
 *     }
 * )
 * @Vich\Uploadable
 */
class DeviceImage
{
    use TimestampTrait;
    use EditorTrait;
    /**
     * @var string
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     *
     * @Assert\Uuid()
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     *
     * @Assert\Length(min="1", max="100")
     */
    private $imageName;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="device_images", fileNameProperty="imageName")
     * @Assert\NotBlank(groups={"creation"})
     * @var File|null
     */
    private $imageFile;
```

When I try to delete it via GraphQL mutation:

```
  deleteDeviceImage(input: {id: "4be27684-bd88-11eb-9bd9-00ff8166658a"}) {
    clientMutationId
  }
```

I get the following error message: 
```
Unhandled Promise rejection: Internal server error ; Zone: <root> ; Task: Promise.then ; Value: Error: Internal server error
    at new ApolloError (index.js:26)
    at Object.next (QueryManager.js:88)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at iteration.js:4
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (iteration.js:4)
    at Object.next (Concast.js:25)
    at notifySubscription (Observable.js:135) Error: Internal server error
    at new ApolloError (http://localhost:8100/vendor.js:62615:28)
    at Object.next (http://localhost:8100/vendor.js:152614:53)
    at notifySubscription (http://localhost:8100/vendor.js:136374:18)
    at onNotify (http://localhost:8100/vendor.js:136418:3)
    at SubscriptionObserver.next (http://localhost:8100/vendor.js:136474:7)
    at http://localhost:8100/vendor.js:1059:68
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (http://localhost:8100/vendor.js:1059:25)
    at Object.next (http://localhost:8100/vendor.js:70868:97)
    at notifySubscription (http://localhost:8100/vendor.js:136374:18)
```

I am very new to web development, and I couldn't find anything helpful so far.

**Comment by garak** [comment]
Default way is using `remove` method in `UploaderHandler` service.

**Comment by Remonell** [comment]
Do I have to implement that handler myself and override the remove method? Where would you suggest I should call that remove method? Do I need to create a separate Controller just for deleting?

**Comment by garak** [comment]
It's a service. Just inject it where you need it.

**Comment by Remonell** [comment]
That is the problem I think. I am not sure where I need it. But I guess that is a doctrine/symfony related issue then. I imagine I have to override the default remove method from doctrine then and replace it with the remove call to the UploaderHandler remove method. But I do not know where to do that. I will need to spend some time reading the doctrine docs I guess. Thank you for your help.
