### ISSUE TITLE
ServiceCircularReferenceException when using gaufrette doctrine storage

### ISSUE THREAD

**Issue by kucharovic** [dustin10/VichUploaderBundle#748]
After updating to v1.4.1 getting this error:

```                                                                                                                                                                 
  [RuntimeException]                                                                                                                                                  
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                           
  PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException' with message 'Circular reference detected  
   for service "doctrine.dbal.default_connection", path: "doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection -> vich_uploader.upload_handler ->  
   vich_uploader.storage -> knp_gaufrette.filesystem_map -> gaufrette.conventions_fs_filesystem".' in /var/www/…/vendor/symfony/symfony/src/Symfony/Component  
  /DependencyInjection/Container.php:305                                                                                                                              
  Stack trace:                                                                                                                                                        
  #0 /var/www/…/var/cache/dev/appDevDebugProjectContainer.php(3047): Symfony\Component\DependencyInjection\Container->get('doctrine.dbal.d...')                
  #1 /var/www/…/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(341): appDevDebugProjectContainer->getGaufrette_ConventionsFsF  
  ilesystemService()                                                                                                                                                  
  #2 /var/www/…/var/cache/dev/appDevDebugProjectContainer.php(3086): Symfony\Component\DependencyInjection\Container->get('gaufrette.conve...')                
  #3 /var/www/…/vend in /var/www/…/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php on line 305                                                                                                                                                                   
```

**Comment by garak** [comment]
You likely need to require `ocramius/proxy-manager` to allow the [lazy service](https://symfony.com/doc/current/service_container/lazy_services.html).

**Comment by kucharovic** [comment]
@garak Yes, it's caused by commit [209510a](https://github.com/dustin10/VichUploaderBundle/commit/209510ace7c218783f5c0528dd0bfa1c89515f69).

**Comment by garak** [comment]
Exactly. We removed that dependency because it's needed only when using Gaufrette

**Comment by kucharovic** [comment]
Oh, I see. Then it would be nice to suggest users to install it manually. To which branch can I submit PR?

**Comment by garak** [comment]
To branch `1.4`.
Thanks

**Comment by kucharovic** [comment]
@garak done. #750
